version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - gosmopolitan
    - iface
    - inamedparam
    - interfacebloat
    - intrange
    - iotamixing
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
  disable: []
  settings:
    errcheck:
      exclude-functions:
        - (io.StringWriter).WriteString
        - (fmt.State).Write
        - (net.Conn).SetDeadline
        - (net.Conn).SetReadDeadline
        - (net.Conn).SetWriteDeadline
        - (net.PacketConn).SetDeadline
        - (net.PacketConn).SetReadDeadline
        - (net.PacketConn).SetWriteDeadline
        - (*github.com/ghettovoice/gosip/internal/ioutil.CountingWriter).Write
        - (*github.com/ghettovoice/gosip/internal/ioutil.CountingWriter).WriteString
        - (github.com/ghettovoice/gosip/internal/types.Renderer).RenderTo
    exhaustive:
      default-signifies-exhaustive: true
    godoclint:
      disable:
        - single-pkg-doc
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
    recvcheck:
      exclusions:
        - "*.UnmarshalJSON"
        - "*.UnmarshalText"
    revive:
      confidence: 0.8
      rules:
        - name: argument-limit
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: true
        - name: blank-imports
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: comment-spacings
          severity: warning
          disabled: false
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: max-control-nesting
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: true
        - name: range-val-in-closure
          severity: warning
          disabled: true
        - name: redefines-builtin-id
          severity: warning
          disabled: true
        - name: redundant-build-tag
          severity: warning
          disabled: false
        - name: redundant-import-alias
          severity: warning
          disabled: false
        - name: redundant-test-main-exit
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: struct-tag
          severity: warning
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        - name: use-any
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
    sloglint:
      attr-only: true
      context: "scope"
      static-msg: true
      msg-style: lowercased
      key-naming-case: snake
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    unparam:
      check-exported: false
    unused:
      local-variables-are-used: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx|ok)" shadows declaration at'
      - linters:
          - gocognit
          - godoclint
          - nilnil
        path: (.+)_(test|deep)\.go
    paths:
      - internal/testutil/netmock/net.go
      - internal/grammar/rfc3261/rules.go
      - internal/grammar/rfc3966/rules.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofumpt:
      extra:
        group-params: true
  exclusions:
    generated: lax
    paths:
      - internal/testutil/netmock/net.go
      - internal/grammar/rfc3261/rules.go
      - internal/grammar/rfc3966/rules.go
      - third_party$
      - builtin$
      - examples$
