// Code generated by abnf. DO NOT EDIT.

package rfc3966

import (
	"sync"

	"github.com/ghettovoice/abnf"
	"github.com/ghettovoice/abnf/pkg/abnf_core"
)

var (
	oprsDescr  = &OperatorsDescr{}
	rulesDescr = &RulesDescr{}
)

// Operators returns operators descriptor.
func Operators() *OperatorsDescr {
	return oprsDescr
}

// Rules returns rules descriptor.
func Rules() *RulesDescr {
	return rulesDescr
}

// OperatorsMap returns map of all operators.
func OperatorsMap() map[string]abnf.Operator {
	return map[string]abnf.Operator{
		"alphanum":             oprsDescr.Alphanum,
		"context":              oprsDescr.Context,
		"descriptor":           oprsDescr.Descriptor,
		"domainlabel":          oprsDescr.Domainlabel,
		"domainname":           oprsDescr.Domainname,
		"escaped":              oprsDescr.Escaped,
		"extension":            oprsDescr.Extension,
		"global-number":        oprsDescr.GlobalNumber,
		"global-number-digits": oprsDescr.GlobalNumberDigits,
		"isdn-subaddress":      oprsDescr.IsdnSubaddress,
		"local-number":         oprsDescr.LocalNumber,
		"local-number-digits":  oprsDescr.LocalNumberDigits,
		"mark":                 oprsDescr.Mark,
		"par":                  oprsDescr.Par,
		"param-unreserved":     oprsDescr.ParamUnreserved,
		"paramchar":            oprsDescr.Paramchar,
		"parameter":            oprsDescr.Parameter,
		"phonedigit":           oprsDescr.Phonedigit,
		"phonedigit-hex":       oprsDescr.PhonedigitHex,
		"pname":                oprsDescr.Pname,
		"pvalue":               oprsDescr.Pvalue,
		"reserved":             oprsDescr.Reserved,
		"telephone-subscriber": oprsDescr.TelephoneSubscriber,
		"telephone-uri":        oprsDescr.TelephoneUri,
		"toplabel":             oprsDescr.Toplabel,
		"unreserved":           oprsDescr.Unreserved,
		"visual-separator":     oprsDescr.VisualSeparator,
	}
}

// RulesMap returns map of all rules.
func RulesMap() map[string]abnf.Rule {
	return map[string]abnf.Rule{
		"alphanum":             rulesDescr.Alphanum,
		"context":              rulesDescr.Context,
		"descriptor":           rulesDescr.Descriptor,
		"domainlabel":          rulesDescr.Domainlabel,
		"domainname":           rulesDescr.Domainname,
		"escaped":              rulesDescr.Escaped,
		"extension":            rulesDescr.Extension,
		"global-number":        rulesDescr.GlobalNumber,
		"global-number-digits": rulesDescr.GlobalNumberDigits,
		"isdn-subaddress":      rulesDescr.IsdnSubaddress,
		"local-number":         rulesDescr.LocalNumber,
		"local-number-digits":  rulesDescr.LocalNumberDigits,
		"mark":                 rulesDescr.Mark,
		"par":                  rulesDescr.Par,
		"param-unreserved":     rulesDescr.ParamUnreserved,
		"paramchar":            rulesDescr.Paramchar,
		"parameter":            rulesDescr.Parameter,
		"phonedigit":           rulesDescr.Phonedigit,
		"phonedigit-hex":       rulesDescr.PhonedigitHex,
		"pname":                rulesDescr.Pname,
		"pvalue":               rulesDescr.Pvalue,
		"reserved":             rulesDescr.Reserved,
		"telephone-subscriber": rulesDescr.TelephoneSubscriber,
		"telephone-uri":        rulesDescr.TelephoneUri,
		"toplabel":             rulesDescr.Toplabel,
		"unreserved":           rulesDescr.Unreserved,
		"visual-separator":     rulesDescr.VisualSeparator,
	}
}

// OperatorsDescr defines operators descriptor that provides operators as methods.
type OperatorsDescr struct {
	alphanum                abnf.Operator
	alphanumOnce            sync.Once
	context                 abnf.Operator
	contextOnce             sync.Once
	descriptor              abnf.Operator
	descriptorOnce          sync.Once
	domainlabel             abnf.Operator
	domainlabelOnce         sync.Once
	domainname              abnf.Operator
	domainnameOnce          sync.Once
	escaped                 abnf.Operator
	escapedOnce             sync.Once
	extension               abnf.Operator
	extensionOnce           sync.Once
	globalNumber            abnf.Operator
	globalNumberOnce        sync.Once
	globalNumberDigits      abnf.Operator
	globalNumberDigitsOnce  sync.Once
	isdnSubaddress          abnf.Operator
	isdnSubaddressOnce      sync.Once
	localNumber             abnf.Operator
	localNumberOnce         sync.Once
	localNumberDigits       abnf.Operator
	localNumberDigitsOnce   sync.Once
	mark                    abnf.Operator
	markOnce                sync.Once
	par                     abnf.Operator
	parOnce                 sync.Once
	paramUnreserved         abnf.Operator
	paramUnreservedOnce     sync.Once
	paramchar               abnf.Operator
	paramcharOnce           sync.Once
	parameter               abnf.Operator
	parameterOnce           sync.Once
	phonedigit              abnf.Operator
	phonedigitOnce          sync.Once
	phonedigitHex           abnf.Operator
	phonedigitHexOnce       sync.Once
	pname                   abnf.Operator
	pnameOnce               sync.Once
	pvalue                  abnf.Operator
	pvalueOnce              sync.Once
	reserved                abnf.Operator
	reservedOnce            sync.Once
	telephoneSubscriber     abnf.Operator
	telephoneSubscriberOnce sync.Once
	telephoneUri            abnf.Operator
	telephoneUriOnce        sync.Once
	toplabel                abnf.Operator
	toplabelOnce            sync.Once
	unreserved              abnf.Operator
	unreservedOnce          sync.Once
	visualSeparator         abnf.Operator
	visualSeparatorOnce     sync.Once
}

// Alphanum operator: alphanum = ALPHA / DIGIT
func (desc *OperatorsDescr) Alphanum(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.alphanumOnce.Do(func() {
		desc.alphanum = abnf.Alt(
			"alphanum",
			abnf_core.Operators().ALPHA,
			abnf_core.Operators().DIGIT,
		)
	})
	return desc.alphanum(in, pos, ns) //errtrace:skip
}

// Context operator: context = ";phone-context=" descriptor
func (desc *OperatorsDescr) Context(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.contextOnce.Do(func() {
		desc.context = abnf.Concat(
			"context",
			abnf.Literal("\";phone-context=\"", []byte{59, 112, 104, 111, 110, 101, 45, 99, 111, 110, 116, 101, 120, 116, 61}),
			desc.Descriptor,
		)
	})
	return desc.context(in, pos, ns) //errtrace:skip
}

// Descriptor operator: descriptor = domainname / global-number-digits
func (desc *OperatorsDescr) Descriptor(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.descriptorOnce.Do(func() {
		desc.descriptor = abnf.Alt(
			"descriptor",
			desc.Domainname,
			desc.GlobalNumberDigits,
		)
	})
	return desc.descriptor(in, pos, ns) //errtrace:skip
}

// Domainlabel operator: domainlabel = alphanum / alphanum *( alphanum / "-" ) alphanum
func (desc *OperatorsDescr) Domainlabel(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.domainlabelOnce.Do(func() {
		desc.domainlabel = abnf.Alt(
			"domainlabel",
			desc.Alphanum,
			abnf.Concat(
				"alphanum *( alphanum / \"-\" ) alphanum",
				desc.Alphanum,
				abnf.Repeat0Inf(
					"*( alphanum / \"-\" )",
					abnf.Alt(
						"alphanum / \"-\"",
						desc.Alphanum,
						abnf.Literal("\"-\"", []byte{45}),
					),
				),
				desc.Alphanum,
			),
		)
	})
	return desc.domainlabel(in, pos, ns) //errtrace:skip
}

// Domainname operator: domainname = *( domainlabel "." ) toplabel [ "." ]
func (desc *OperatorsDescr) Domainname(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.domainnameOnce.Do(func() {
		desc.domainname = abnf.Concat(
			"domainname",
			abnf.Repeat0Inf(
				"*( domainlabel \".\" )",
				abnf.Concat(
					"domainlabel \".\"",
					desc.Domainlabel,
					abnf.Literal("\".\"", []byte{46}),
				),
			),
			desc.Toplabel,
			abnf.Optional(
				"[ \".\" ]",
				abnf.Literal("\".\"", []byte{46}),
			),
		)
	})
	return desc.domainname(in, pos, ns) //errtrace:skip
}

// Escaped operator: escaped = "%" HEXDIG HEXDIG
func (desc *OperatorsDescr) Escaped(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.escapedOnce.Do(func() {
		desc.escaped = abnf.Concat(
			"escaped",
			abnf.Literal("\"%\"", []byte{37}),
			abnf_core.Operators().HEXDIG,
			abnf_core.Operators().HEXDIG,
		)
	})
	return desc.escaped(in, pos, ns) //errtrace:skip
}

// Extension operator: extension = ";ext=" 1*phonedigit
func (desc *OperatorsDescr) Extension(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.extensionOnce.Do(func() {
		desc.extension = abnf.Concat(
			"extension",
			abnf.Literal("\";ext=\"", []byte{59, 101, 120, 116, 61}),
			abnf.Repeat1Inf(
				"1*phonedigit",
				desc.Phonedigit,
			),
		)
	})
	return desc.extension(in, pos, ns) //errtrace:skip
}

// GlobalNumber operator: global-number = global-number-digits *par
func (desc *OperatorsDescr) GlobalNumber(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.globalNumberOnce.Do(func() {
		desc.globalNumber = abnf.Concat(
			"global-number",
			desc.GlobalNumberDigits,
			abnf.Repeat0Inf(
				"*par",
				desc.Par,
			),
		)
	})
	return desc.globalNumber(in, pos, ns) //errtrace:skip
}

// GlobalNumberDigits operator: global-number-digits = "+" *phonedigit DIGIT *phonedigit
func (desc *OperatorsDescr) GlobalNumberDigits(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.globalNumberDigitsOnce.Do(func() {
		desc.globalNumberDigits = abnf.Concat(
			"global-number-digits",
			abnf.Literal("\"+\"", []byte{43}),
			abnf.Repeat0Inf(
				"*phonedigit",
				desc.Phonedigit,
			),
			abnf_core.Operators().DIGIT,
			abnf.Repeat0Inf(
				"*phonedigit",
				desc.Phonedigit,
			),
		)
	})
	return desc.globalNumberDigits(in, pos, ns) //errtrace:skip
}

// IsdnSubaddress operator: isdn-subaddress = ";isub=" 1*paramchar
func (desc *OperatorsDescr) IsdnSubaddress(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.isdnSubaddressOnce.Do(func() {
		desc.isdnSubaddress = abnf.Concat(
			"isdn-subaddress",
			abnf.Literal("\";isub=\"", []byte{59, 105, 115, 117, 98, 61}),
			abnf.Repeat1Inf(
				"1*paramchar",
				desc.Paramchar,
			),
		)
	})
	return desc.isdnSubaddress(in, pos, ns) //errtrace:skip
}

// LocalNumber operator: local-number = local-number-digits *par context *par
func (desc *OperatorsDescr) LocalNumber(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.localNumberOnce.Do(func() {
		desc.localNumber = abnf.Concat(
			"local-number",
			desc.LocalNumberDigits,
			abnf.Repeat0Inf(
				"*par",
				desc.Par,
			),
			desc.Context,
			abnf.Repeat0Inf(
				"*par",
				desc.Par,
			),
		)
	})
	return desc.localNumber(in, pos, ns) //errtrace:skip
}

// LocalNumberDigits operator: local-number-digits = *phonedigit-hex ( HEXDIG / "*" / "#" ) *phonedigit-hex
func (desc *OperatorsDescr) LocalNumberDigits(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.localNumberDigitsOnce.Do(func() {
		desc.localNumberDigits = abnf.Concat(
			"local-number-digits",
			abnf.Repeat0Inf(
				"*phonedigit-hex",
				desc.PhonedigitHex,
			),
			abnf.Alt(
				"HEXDIG / \"*\" / \"#\"",
				abnf_core.Operators().HEXDIG,
				abnf.Literal("\"*\"", []byte{42}),
				abnf.Literal("\"#\"", []byte{35}),
			),
			abnf.Repeat0Inf(
				"*phonedigit-hex",
				desc.PhonedigitHex,
			),
		)
	})
	return desc.localNumberDigits(in, pos, ns) //errtrace:skip
}

// Mark operator: mark = "-" / "_" / "." / "!" / "~" / "*" / "'" / "(" / ")"
func (desc *OperatorsDescr) Mark(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.markOnce.Do(func() {
		desc.mark = abnf.Alt(
			"mark",
			abnf.Literal("\"-\"", []byte{45}),
			abnf.Literal("\"_\"", []byte{95}),
			abnf.Literal("\".\"", []byte{46}),
			abnf.Literal("\"!\"", []byte{33}),
			abnf.Literal("\"~\"", []byte{126}),
			abnf.Literal("\"*\"", []byte{42}),
			abnf.Literal("\"'\"", []byte{39}),
			abnf.Literal("\"(\"", []byte{40}),
			abnf.Literal("\")\"", []byte{41}),
		)
	})
	return desc.mark(in, pos, ns) //errtrace:skip
}

// Par operator: par = extension / isdn-subaddress / parameter
func (desc *OperatorsDescr) Par(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.parOnce.Do(func() {
		desc.par = abnf.Alt(
			"par",
			desc.Extension,
			desc.IsdnSubaddress,
			desc.Parameter,
		)
	})
	return desc.par(in, pos, ns) //errtrace:skip
}

// ParamUnreserved operator: param-unreserved = "[" / "]" / "/" / ":" / "&" / "+" / "$"
func (desc *OperatorsDescr) ParamUnreserved(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.paramUnreservedOnce.Do(func() {
		desc.paramUnreserved = abnf.Alt(
			"param-unreserved",
			abnf.Literal("\"[\"", []byte{91}),
			abnf.Literal("\"]\"", []byte{93}),
			abnf.Literal("\"/\"", []byte{47}),
			abnf.Literal("\":\"", []byte{58}),
			abnf.Literal("\"&\"", []byte{38}),
			abnf.Literal("\"+\"", []byte{43}),
			abnf.Literal("\"$\"", []byte{36}),
		)
	})
	return desc.paramUnreserved(in, pos, ns) //errtrace:skip
}

// Paramchar operator: paramchar = param-unreserved / unreserved / escaped
func (desc *OperatorsDescr) Paramchar(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.paramcharOnce.Do(func() {
		desc.paramchar = abnf.Alt(
			"paramchar",
			desc.ParamUnreserved,
			desc.Unreserved,
			desc.Escaped,
		)
	})
	return desc.paramchar(in, pos, ns) //errtrace:skip
}

// Parameter operator: parameter = ";" pname ["=" pvalue ]
func (desc *OperatorsDescr) Parameter(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.parameterOnce.Do(func() {
		desc.parameter = abnf.Concat(
			"parameter",
			abnf.Literal("\";\"", []byte{59}),
			desc.Pname,
			abnf.Optional(
				"[\"=\" pvalue ]",
				abnf.Concat(
					"\"=\" pvalue",
					abnf.Literal("\"=\"", []byte{61}),
					desc.Pvalue,
				),
			),
		)
	})
	return desc.parameter(in, pos, ns) //errtrace:skip
}

// Phonedigit operator: phonedigit = DIGIT / visual-separator
func (desc *OperatorsDescr) Phonedigit(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.phonedigitOnce.Do(func() {
		desc.phonedigit = abnf.Alt(
			"phonedigit",
			abnf_core.Operators().DIGIT,
			desc.VisualSeparator,
		)
	})
	return desc.phonedigit(in, pos, ns) //errtrace:skip
}

// PhonedigitHex operator: phonedigit-hex = HEXDIG / "*" / "#" / visual-separator
func (desc *OperatorsDescr) PhonedigitHex(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.phonedigitHexOnce.Do(func() {
		desc.phonedigitHex = abnf.Alt(
			"phonedigit-hex",
			abnf_core.Operators().HEXDIG,
			abnf.Literal("\"*\"", []byte{42}),
			abnf.Literal("\"#\"", []byte{35}),
			desc.VisualSeparator,
		)
	})
	return desc.phonedigitHex(in, pos, ns) //errtrace:skip
}

// Pname operator: pname = 1*( alphanum / "-" )
func (desc *OperatorsDescr) Pname(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.pnameOnce.Do(func() {
		desc.pname = abnf.Repeat1Inf(
			"pname",
			abnf.Alt(
				"alphanum / \"-\"",
				desc.Alphanum,
				abnf.Literal("\"-\"", []byte{45}),
			),
		)
	})
	return desc.pname(in, pos, ns) //errtrace:skip
}

// Pvalue operator: pvalue = 1*paramchar
func (desc *OperatorsDescr) Pvalue(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.pvalueOnce.Do(func() {
		desc.pvalue = abnf.Repeat1Inf(
			"pvalue",
			desc.Paramchar,
		)
	})
	return desc.pvalue(in, pos, ns) //errtrace:skip
}

// Reserved operator: reserved = ";" / "/" / "?" / ":" / "@" / "&" / "=" / "+" / "$" / ","
func (desc *OperatorsDescr) Reserved(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.reservedOnce.Do(func() {
		desc.reserved = abnf.Alt(
			"reserved",
			abnf.Literal("\";\"", []byte{59}),
			abnf.Literal("\"/\"", []byte{47}),
			abnf.Literal("\"?\"", []byte{63}),
			abnf.Literal("\":\"", []byte{58}),
			abnf.Literal("\"@\"", []byte{64}),
			abnf.Literal("\"&\"", []byte{38}),
			abnf.Literal("\"=\"", []byte{61}),
			abnf.Literal("\"+\"", []byte{43}),
			abnf.Literal("\"$\"", []byte{36}),
			abnf.Literal("\",\"", []byte{44}),
		)
	})
	return desc.reserved(in, pos, ns) //errtrace:skip
}

// TelephoneSubscriber operator: telephone-subscriber = global-number / local-number
func (desc *OperatorsDescr) TelephoneSubscriber(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.telephoneSubscriberOnce.Do(func() {
		desc.telephoneSubscriber = abnf.Alt(
			"telephone-subscriber",
			desc.GlobalNumber,
			desc.LocalNumber,
		)
	})
	return desc.telephoneSubscriber(in, pos, ns) //errtrace:skip
}

// TelephoneUri operator: telephone-uri = "tel:" telephone-subscriber
func (desc *OperatorsDescr) TelephoneUri(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.telephoneUriOnce.Do(func() {
		desc.telephoneUri = abnf.Concat(
			"telephone-uri",
			abnf.Literal("\"tel:\"", []byte{116, 101, 108, 58}),
			desc.TelephoneSubscriber,
		)
	})
	return desc.telephoneUri(in, pos, ns) //errtrace:skip
}

// Toplabel operator: toplabel = ALPHA / ALPHA *( alphanum / "-" ) alphanum
func (desc *OperatorsDescr) Toplabel(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.toplabelOnce.Do(func() {
		desc.toplabel = abnf.Alt(
			"toplabel",
			abnf_core.Operators().ALPHA,
			abnf.Concat(
				"ALPHA *( alphanum / \"-\" ) alphanum",
				abnf_core.Operators().ALPHA,
				abnf.Repeat0Inf(
					"*( alphanum / \"-\" )",
					abnf.Alt(
						"alphanum / \"-\"",
						desc.Alphanum,
						abnf.Literal("\"-\"", []byte{45}),
					),
				),
				desc.Alphanum,
			),
		)
	})
	return desc.toplabel(in, pos, ns) //errtrace:skip
}

// Unreserved operator: unreserved = alphanum / mark
func (desc *OperatorsDescr) Unreserved(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.unreservedOnce.Do(func() {
		desc.unreserved = abnf.Alt(
			"unreserved",
			desc.Alphanum,
			desc.Mark,
		)
	})
	return desc.unreserved(in, pos, ns) //errtrace:skip
}

// VisualSeparator operator: visual-separator = "-" / "." / "(" / ")"
func (desc *OperatorsDescr) VisualSeparator(in []byte, pos uint, ns *abnf.Nodes) error {
	desc.visualSeparatorOnce.Do(func() {
		desc.visualSeparator = abnf.Alt(
			"visual-separator",
			abnf.Literal("\"-\"", []byte{45}),
			abnf.Literal("\".\"", []byte{46}),
			abnf.Literal("\"(\"", []byte{40}),
			abnf.Literal("\")\"", []byte{41}),
		)
	})
	return desc.visualSeparator(in, pos, ns) //errtrace:skip
}

// RulesDescr defines rules descriptor that provides rules as methods.
type RulesDescr struct{}

// Alphanum rule: alphanum = ALPHA / DIGIT
func (*RulesDescr) Alphanum(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Alphanum(in, 0, ns) //errtrace:skip
}

// Context rule: context = ";phone-context=" descriptor
func (*RulesDescr) Context(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Context(in, 0, ns) //errtrace:skip
}

// Descriptor rule: descriptor = domainname / global-number-digits
func (*RulesDescr) Descriptor(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Descriptor(in, 0, ns) //errtrace:skip
}

// Domainlabel rule: domainlabel = alphanum / alphanum *( alphanum / "-" ) alphanum
func (*RulesDescr) Domainlabel(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Domainlabel(in, 0, ns) //errtrace:skip
}

// Domainname rule: domainname = *( domainlabel "." ) toplabel [ "." ]
func (*RulesDescr) Domainname(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Domainname(in, 0, ns) //errtrace:skip
}

// Escaped rule: escaped = "%" HEXDIG HEXDIG
func (*RulesDescr) Escaped(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Escaped(in, 0, ns) //errtrace:skip
}

// Extension rule: extension = ";ext=" 1*phonedigit
func (*RulesDescr) Extension(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Extension(in, 0, ns) //errtrace:skip
}

// GlobalNumber rule: global-number = global-number-digits *par
func (*RulesDescr) GlobalNumber(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.GlobalNumber(in, 0, ns) //errtrace:skip
}

// GlobalNumberDigits rule: global-number-digits = "+" *phonedigit DIGIT *phonedigit
func (*RulesDescr) GlobalNumberDigits(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.GlobalNumberDigits(in, 0, ns) //errtrace:skip
}

// IsdnSubaddress rule: isdn-subaddress = ";isub=" 1*paramchar
func (*RulesDescr) IsdnSubaddress(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.IsdnSubaddress(in, 0, ns) //errtrace:skip
}

// LocalNumber rule: local-number = local-number-digits *par context *par
func (*RulesDescr) LocalNumber(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.LocalNumber(in, 0, ns) //errtrace:skip
}

// LocalNumberDigits rule: local-number-digits = *phonedigit-hex ( HEXDIG / "*" / "#" ) *phonedigit-hex
func (*RulesDescr) LocalNumberDigits(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.LocalNumberDigits(in, 0, ns) //errtrace:skip
}

// Mark rule: mark = "-" / "_" / "." / "!" / "~" / "*" / "'" / "(" / ")"
func (*RulesDescr) Mark(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Mark(in, 0, ns) //errtrace:skip
}

// Par rule: par = extension / isdn-subaddress / parameter
func (*RulesDescr) Par(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Par(in, 0, ns) //errtrace:skip
}

// ParamUnreserved rule: param-unreserved = "[" / "]" / "/" / ":" / "&" / "+" / "$"
func (*RulesDescr) ParamUnreserved(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.ParamUnreserved(in, 0, ns) //errtrace:skip
}

// Paramchar rule: paramchar = param-unreserved / unreserved / escaped
func (*RulesDescr) Paramchar(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Paramchar(in, 0, ns) //errtrace:skip
}

// Parameter rule: parameter = ";" pname ["=" pvalue ]
func (*RulesDescr) Parameter(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Parameter(in, 0, ns) //errtrace:skip
}

// Phonedigit rule: phonedigit = DIGIT / visual-separator
func (*RulesDescr) Phonedigit(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Phonedigit(in, 0, ns) //errtrace:skip
}

// PhonedigitHex rule: phonedigit-hex = HEXDIG / "*" / "#" / visual-separator
func (*RulesDescr) PhonedigitHex(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.PhonedigitHex(in, 0, ns) //errtrace:skip
}

// Pname rule: pname = 1*( alphanum / "-" )
func (*RulesDescr) Pname(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Pname(in, 0, ns) //errtrace:skip
}

// Pvalue rule: pvalue = 1*paramchar
func (*RulesDescr) Pvalue(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Pvalue(in, 0, ns) //errtrace:skip
}

// Reserved rule: reserved = ";" / "/" / "?" / ":" / "@" / "&" / "=" / "+" / "$" / ","
func (*RulesDescr) Reserved(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Reserved(in, 0, ns) //errtrace:skip
}

// TelephoneSubscriber rule: telephone-subscriber = global-number / local-number
func (*RulesDescr) TelephoneSubscriber(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.TelephoneSubscriber(in, 0, ns) //errtrace:skip
}

// TelephoneUri rule: telephone-uri = "tel:" telephone-subscriber
func (*RulesDescr) TelephoneUri(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.TelephoneUri(in, 0, ns) //errtrace:skip
}

// Toplabel rule: toplabel = ALPHA / ALPHA *( alphanum / "-" ) alphanum
func (*RulesDescr) Toplabel(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Toplabel(in, 0, ns) //errtrace:skip
}

// Unreserved rule: unreserved = alphanum / mark
func (*RulesDescr) Unreserved(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.Unreserved(in, 0, ns) //errtrace:skip
}

// VisualSeparator rule: visual-separator = "-" / "." / "(" / ")"
func (*RulesDescr) VisualSeparator(in []byte, ns *abnf.Nodes) error {
	return oprsDescr.VisualSeparator(in, 0, ns) //errtrace:skip
}
